project:
  type: website
  output-dir: _site

website:
  title: "Paul Foster - Advent of Code"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/pf981/pf981.github.io
format:
  html:
    theme: lux
    css: styles.css

editor: source

