---
title: "2023 Day 7"
subtitle: "Camel Cards"
date: 2024-04-03
categories: [python, easy]
draft: false
knitr:
  opts_chunk: 
    comment: "#>"
    collapse: true
problem_url: "https://adventofcode.com/2023/day/7"
description: "Easy puzzle evaluating simplified poker hands."
image: "/images/2023-07.svg"
---

::: {.hidden}
$$
\newcommand{\blue}[1]{\color{##1577A0}\textbf{#1}\color{##55595C}}
\newcommand{\orange}[1]{\color{##91672C}\textbf{#1}\color{##55595C}}
\newcommand{\red}[1]{\color{##BE4844}\textbf{#1}\color{##55595C}}
\newcommand{\green}[1]{\color{##2F7E4A}\textbf{#1}\color{##55595C}}
\newcommand{\grey}[1]{\color{##969696}{#1}\color{##55595C}}
\newcommand{\greyred}[1]{\color{##f27d79}{#1}\color{##55595C}}
\newcommand{\greygreen}[1]{\color{##7ec295}{#1}\color{##55595C}}
\newcommand{\greyblue}[1]{\color{##76acc2}{#1}\color{##55595C}}
\newcommand{\plus}{\smash{\lower{0.5pc}\grey{+}}}
$$
:::


Ho ho ho, fellow adventurers!

[Advent of Code day 7]({{< meta problem_url >}}) invites us to play a game of Camel Cards. In this simplified version of poker, we must evaluate and rank hands.

First, we'll read the input.
```{python}
with open('input.txt', "r") as f:
    lines = f.readlines()
```

## Part 1 <small class="text-body-secondary">Hand Hierarchy</small>

::::: {.p-0 style="min-width: fit-content;"}

```{=html}
<div class="card border-secondary mb-3 mx-auto">
  <div class="card-body p-3 m-1 pb-0 mb-0">
    <h4 class="card-title mt-0">Task 1</h4>
```

You are given a list of 5 card hands and their corresponding <b class='fw-bold' style='color: #2F7E4A;'>bids</b>. <b class='fw-bold' style='color: #1577A0;'>Rank</b> each hand and calculate the winnings as the product of the <b class='fw-bold' style='color: #1577A0;'>rank</b> and <b class='fw-bold' style='color: #2F7E4A;'>bid</b>. Compute the <b class='fw-bold' style='color: #91672C;'>total winnings</b>.

Hands are <b class='fw-bold' style='color: #1577A0;'>ranked</b> by their type. If two hands are of the same type, their ordering is then determined by comparing the strength of the individual cards, starting from the first card to the fifth, as needed.

Hand types are ranked as follows:

1. High card
2. One pair
3. Two pair
4. Three of a kind
5. Full house
6. Four of a kind
7. Five of a kind

<h6 class="card-subtitle text-muted">Example</h6>
<!-- &{\text{Hand}} &&{\text{Bid}} &&{\text{\grey{Rank}}} &&{\text{\grey{Type}}}\phantom{\Huge{G}}&{\text{\grey{Winnings}}} &\\ -->

$$
\begin{aligned}
&{\text{Hand}} &&{\text{Bid}} &&{\text{\grey{Rank}}} &&{\text{\grey{Type}}}\phantom{\Huge{g}}&{\text{\grey{Winnings}}} &\\
&\text{32T3K} &&\green{765} &&\greyblue{1} &&\text{\grey{One pair}}          &\greygreen{765} \,\grey{\times}\, \greyblue{1}                                                        &\plus\\
&\text{T55J5} &&\green{684} &&\greyblue{4} &&\text{\grey{Full house}}        &\greygreen{684} \,\grey{\times}\, \greyblue{4}                                                        &\plus\\
&\text{KK677} &&\green{28}  &&\greyblue{3} &&\text{\grey{Two pair}} & \greygreen{28} \,\grey{\times}\, \greyblue{3}                                                        &\plus\\
&\text{KTJJT} &&\green{220} &&\greyblue{2} &&\text{\grey{Two pair}}\grey{^*}          &\greygreen{220} \,\grey{\times}\, \greyblue{2}                                                        &\plus\\
&\text{QQQJA} &&\green{483} &&\greyblue{5} &&\text{\grey{Three of a kind}}   &\greygreen{483} \,\grey{\times}\, \greyblue{5} \llap{\lower{0.4pc}\underline{\phantom{483 \times 5}}} &\\
&             &&            &&             &&                                &\orange{6440}                                                                                         &\\
\end{aligned}
$$

$\grey{\scriptsize{^{*}\text{Second card ranks lower than other two pair's second card}}}$


```{=html}
  </div>
</div>
```

:::::

<div style="clear: both;"></div> 


We'll need a mechanism to rank hands. First, we define a function, `primary_order`, which ranks the hand's type. This is accomplished by analysing the frequency of each card in the hand, allowing us to classify the hand based on predefined patterns.

```{python}
import collections


def primary_order(hand):
    counts = [count for card, count in collections.Counter(hand).most_common()]

    possible_counts = [
        [1, 1, 1, 1, 1],  # High card
        [2, 1, 1, 1],  # One pair
        [2, 2, 1],  # Two pair
        [3, 1, 1],  # Three of a kind
        [3, 2],  # Full house
        [4, 1],  # Four of a kind
        [5],  # Five of a kind
    ]

    return possible_counts.index(counts)
```

Next, we define a function, `secondary_order`, which ranks hands based on the individual card values.

```{python}
def secondary_order(hand):
    return tuple("23456789TJQKA".index(card) for card in hand)
```

Finally, define `hand_bid_order` as the combination of the primary and secondary orderings.  Python makes it easy to combine and apply our primary and secondary orderings. We can provide `sort` a `key` function which takes an element and returns a `tuple` of the primary and secondary orderings.

Calculate the <b class='fw-bold' style='color: #91672C;'>total winnings</b> as the sum of bids multiplied by the <b class='fw-bold' style='color: #1577A0;'>rank</b>.

```{python}
def hand_bid_order(hand_bid):
    hand, bid = hand_bid
    return primary_order(hand), secondary_order(hand)


hands_bids = [line.split(" ") for line in lines]
hands_bids.sort(key=hand_bid_order)
answer1 = sum(i * int(bid) for i, (_, bid) in enumerate(hands_bids, 1))
print(answer1)
```

```{=html}
<div class="card border-info mb-3 mx-auto">
  <div class="card-header text-white bg-info">Key Points</div>
  <div class="card-body p-1">
    <p class="card-text">
```

* Ranking Camel Cards hands involves two levels of ordering:
    1. **Primary ordering** is based on the type of hand, determined by the pattern of card frequencies
    2. **Secondary ordering** evaluates the specific values of the cards within a hand
* * A combined key function, `hand_bid_order`, uses both the primary and secondary orderings to sort the hands from weakest to strongest
```{=html}
    </p>
  </div>
</div>
```


## Part 2 <small class="text-body-secondary">Jokers Wild</small>

::::: {.p-0 style="min-width: fit-content;"}

:::: {.pe-4}
```{=html}
<div class="card border-secondary mb-3 mx-auto">
  <div class="card-body p-3 m-1 pb-0 mb-0">
    <h4 class="card-title mt-0">Task 2</h4>
```

<b class='fw-bold' style='color: #BE4844;'>J</b>s are now wild <b class='fw-bold' style='color: #BE4844;'>Jokers</b> and act as whatever card results in the **strongest type**.

Determine the new hand <b class='fw-bold' style='color: #1577A0;'>ranks</b> and compute the <b class='fw-bold' style='color: #91672C;'>total winnings</b>.

<h6 class="card-subtitle text-muted">Example</h6>
$$
\begin{aligned}
&{\text{Hand}}      &&{\text{Bid}} &&{\text{\grey{Rank}}} &&{\text{\grey{Type}}}\phantom{\Huge{g}}&{\text{\grey{Winnings}}} &\\
&\text{32T3K}       &&\green{765} &&\greyblue{1} &&\text{\grey{One pair}}          &\greygreen{765} \,\grey{\times}\, \greyblue{1}                                                        &\plus\\
&\text{T55\red{J}5} &&\green{684} &&\greyblue{3} &&\text{\grey{Four of a kind}}        &\greygreen{684} \,\grey{\times}\, \greyblue{3}                                                        &\plus\\
&\text{KK677}       &&\green{28}  &&\greyblue{2} &&\text{\grey{Two pair}} & \greygreen{28} \,\grey{\times}\, \greyblue{2}                                                        &\plus\\
&\text{KT\red{JJ}T} &&\green{220} &&\greyblue{5} &&\text{\grey{Four of a kind}}          &\greygreen{220} \,\grey{\times}\, \greyblue{5}                                                        &\plus\\
&\text{QQQ\red{J}A} &&\green{483} &&\greyblue{4} &&\text{\grey{Four of a kind}}   &\greygreen{483} \,\grey{\times}\, \greyblue{4} \llap{\lower{0.4pc}\underline{\phantom{483 \times 4}}} &\\
&                   &&            &&             &&                                &\orange{5905}                                                                                         &\\
\end{aligned}
$$

```{=html}
  </div>
</div>
```
::::
:::::


<div style="clear: both;"></div> 

Create a new function, `hand_bid_order_wild`, which evaluates the maximum potential strength of a hand by considering all possible substitutions of <b class='fw-bold' style='color: #BE4844;'>J</b> with other cards.

```{python}
def hand_bid_order_wild(hand_bid):
    hand, bid = hand_bid
    return (
        max(primary_order(hand.replace("J", c)) for c in "23456789TQKA"),
        secondary_order(hand),
    )


hands_bids.sort(key=hand_bid_order_wild)
answer2 = sum(i * int(bid) for i, (_, bid) in enumerate(hands_bids, 1))
print(answer2)
```


```{=html}
<div class="card border-info mb-3 mx-auto">
  <div class="card-header text-white bg-info">Key Points</div>
  <div class="card-body p-1">
    <p class="card-text">
```

* Compute the max `primary_order` when replacing <b class='fw-bold' style='color: #BE4844;'>J</b>s with every other card
* <b class='fw-bold' style='color: #BE4844;'>Jokers</b> only affect the `primary_order` - the `secondary_order` is calculated the same way
```{=html}
    </p>
  </div>
</div>
```


{{< include ../../_button_footer.qmd >}}
