```{r}
#| echo: false
python_execution_seconds <- function(file_path) {
  tictoc::tic()
  reticulate::py_run_file(file_path)
  elapsed <- tictoc::toc()$toc
  
  tictoc::tic()
  reticulate::py_run_string("")
  reticulate_overhead <- tictoc::toc()$toc
  
  max(elapsed - reticulate_overhead, 0.01)
}
```

```{=html}
<!-- Buttons -->
<div class="d-grid gap-2 d-md-flex justify-content-md-end">

  <!-- Problem Button -->
  <a type="button" class="btn btn-secondary" href="{{< meta problem_url >}}" role="button">
    <i class="bi bi-box-arrow-up-right"></i> Problem
  </a>

  <!-- Input Button -->
  <button type="button" class="btn btn-secondary" data-bs-toggle="modal" data-bs-target="#inputModal">
    <i class="bi bi-file-earmark-text"></i> Input
  </button>

  <!-- Solution Modal Button -->
  <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#solutionModal">
    <i class="bi bi-code-slash"></i> Full Solution
  </button>

</div>


<!-- Input Modal -->
<div class="modal fade" id="inputModal" tabindex="-1" aria-labelledby="inputModalLabel" aria-hidden="true">
<div class="modal-dialog modal-dialog-scrollable modal-xl">
<div class="modal-content">
<div class="modal-header">
  <h5 class="modal-title" id="inputModalLabel">{{< meta title >}} Input</h5>
  <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
</div>
<div class="modal-body">
```
```{r}
#| file: input.txt
#| eval: false
```

```{=html}
</div>
<div class="modal-footer">
</div>
</div>
</div>
</div>


<!-- Solution Modal -->
<div class="modal fade" id="solutionModal" tabindex="-1" aria-labelledby="solutionModalLabel" aria-hidden="true">
<div class="modal-dialog modal-dialog-scrollable modal-xl">
<div class="modal-content">
<div class="modal-header">
  <h5 class="modal-title" id="solutionModalLabel">{{< meta title >}} Full Solution</h5>
  <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
</div>
<div class="modal-body">
```
```{r}
#| file: solution.py
#| eval: false
```

```{=html}
</div>
<div class="modal-footer">
<small><i>Execution took `r python_execution_seconds("solution.py")` seconds</i></small>
</div>
</div>
</div>
</div>
```
